<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\View\Options */
?>

<?php $_options = $block->decorateArray($block->getOptions()) ?>
<?php $_productId = $block->getProduct()->getId() ?>
<?php $sku = $block->getProduct()->getSku(); ?>
<?php if (count($_options)):?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "priceOptions": {
                "optionConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>,
                "controlContainer": ".field",
                "priceHolderSelector": "[data-product-id='<?= $block->escapeHtml($_productId) ?>'][data-role=priceBox]"
            }
        },
        "body" : {
             "customjs":
                    {                        
                        "sku": "<?php echo $sku ?>",
                        "url": "<?php echo $this->helper('M2\Baseprice\Helper\Data')->getGeneralConfig('url') ?>"
                    }
        }
    }
</script>
<?php foreach ($_options as $_option): ?>
        <?= $block->getOptionHtml($_option) ?>
    <?php endforeach; ?>
<?php endif; ?>
<!--<button type="button" title="Check Price" class="action primary tocart"
	id="product-price-button">
	<span><?= $block->escapeHtml(__('Check Price')) ?></span>
</button> --->